version: '2.1'

services:
  frontend:
    image: unicef/donor-reporting-portal-frontend:dev
#    volumes:
#      - "./donor-reporting-portal-frontend:/code"
#    command: ${FE_COMMAND:-sh -c "npm start"}
    container_name: donor_reporting_portal_frontend
    labels:
      - traefik.backend=frontend
      - traefik.frontend.rule=PathPrefix:/
      - traefik.priority=1
      - traefik.enable=true
      - traefik.port=3000

  backend:
    image: unicef/donor-reporting-portal-backend:dev
    env_file: .donor-reporting-portal-backend/.env

    environment:
      DATABASE_URL: postgres://postgres:@db:5432/donor_reporting_portal
      DEBUG: 1
      CACHE_URL: redis://redis:6379/1
      CELERY_BROKER_URL: redis://redis:6379/2
      CELERY_RESULT_BACKEND: redis://redis:6379/3
      CSRF_COOKIE_SECURE: 0
      REQUIREMENTS: -d
      AZURE_TENANT: nikunicef.onmicrosoft.com
      FLOWER_PWD: 123
      SECURE_SSL_REDIRECT: 0
      SESSION_COOKIE_HTTPONLY: 0
      SESSION_COOKIE_SECURE: 0
      STATIC_ROOT: /var/donor_reporting_portal/static/
      MEDIA_ROOT: /var/donor_reporting_portal/media/
      MEDIA_URL: http://localhost:8081/media/
      SUPERVISOR_PWD: 123

    volumes:
      - "./donor-reporting-portal-backend:/code"
      - "./volumes/backend/var/donor_reporting_portal/:/var/donor_reporting_portal"
    depends_on:
      - db
      - redis
    container_name: donor_reporting_portal_backend
    labels:
      - traefik.backend=backend
      - traefik.frontend.rule=PathPrefix:/api/,/admin/,/static/,/sociallogin/,/socialcomplete/
      - traefik.priority=2
      - traefik.enable=true
      - traefik.port=8000

  proxy:
    image: traefik:v1.7
    command: --api --docker
    ports:
      - "8082:80"
      - "8080:8080"
    container_name: donor_reporting_portal_proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  db:
    image: mdillon/postgis:9.6-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: donor_reporting_portal
    volumes:
      - "./volumes/db2/data:/var/lib/postgresql/data"
    container_name: donor_reporting_portal_db

  redis:
    image: redis
    container_name: donor_reporting_portal_redis
    hostname: redis
    command: ["redis-server", "--appendonly", "yes"]
