version: '3.8'

services:

  backend:
    image: unicef/donor-reporting-portal-backend:dev
    env_file: ./donor-reporting-portal-backend/.env

    environment:
      DATABASE_URL: postgres://postgres:pass@db:5432/donor_reporting_portal
      HOST: http://localhost
      DEBUG: 1
      CACHE_URL: redis://redis:6379/1
      REDIS_URL: redis://redis:6379/1
      CELERY_BROKER_URL: redis://redis:6379/2
      CELERY_RESULT_BACKEND: redis://redis:6379/3
      CSRF_COOKIE_SECURE: 0
      SECURE_SSL_REDIRECT: 0
      SESSION_COOKIE_HTTPONLY: 0
      SESSION_COOKIE_SECURE: 0
      STATIC_ROOT: /var/donor_reporting_portal/static/
      MEDIA_ROOT: /var/donor_reporting_portal/media/
      MEDIA_URL: http://localhost/media/

    volumes:
      - "./donor-reporting-portal-backend:/code"
      - "./volumes/backend/var/donor_reporting_portal/:/var/donor_reporting_portal"
    depends_on:
      - db
      - redis
    container_name: donor_reporting_portal_backend
    labels:
      traefik.http.routers.backend.rule: Host(`localhost`) && PathPrefix(`/api/`, `/admin/`, `/static/`, `/security/`, `/social/`, `/accounts/`, `/manage/`)

  frontend:
    image: unicef/donor-reporting-portal-frontend:develop
    container_name: donor_reporting_portal_frontend
    labels:
      traefik.http.routers.frontend.rule: Host(`localhost`)

#  frontend:
#    build:
#      context: ./donor-reporting-portal-frontend
#      dockerfile: Dockerfile-dev
#    image: unicef/donor-reporting-portal-frontend:build
#    container_name: donor_reporting_portal_frontend_build
#    volumes:
#      - "./donor-reporting-portal-frontend:/code"
#    command: sh -c "npm run start"
#    labels:
#      traefik.http.routers.frontend.rule: Host(`localhost`)
#      traefik.http.services.fronted.loadBalancer.server.port: 3000

  proxy:
    image: traefik:v2.4
    container_name: donor_reporting_portal_proxy
    command:
      - --api.insecure=true
      - --entrypoints.web.address=:80
      - --providers.docker
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      traefik.http.routers.dash.rule: Host(`dash.localhost`)
      traefik.http.routers.dash.service: api@internal

  db:
    image: postgres:12-alpine
    container_name: donor_reporting_portal_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: donor_reporting_portal
    volumes:
      - "./volumes/db2/data:/var/lib/postgresql/data"

  redis:
    image: redis:6.2-alpine
    container_name: donor_reporting_portal_redis
    hostname: redis
    command: ["redis-server", "--appendonly", "yes"]
